apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/jobset/releases/download/v0.8.2/manifests.yaml

# Add required patches.
patches:
  # Remove namespace from the JobSet release manifests.
  - path: patches/jobset_remove_namespace.yaml
    target:
      group: ""
      version: v1
      kind: Namespace
  - target:
      kind: Deployment
      name: jobset-controller-manager
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/sidecar.istio.io~1inject
        value: "false"
  - target:
      kind: Deployment
      name: jobset-controller-manager
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/control-plane
        value: kubeflow-trainer-v2-jobset
  - target:
      kind: Deployment
      name: jobset-controller-manager
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/control-plane
        value: kubeflow-trainer-v2-jobset

  - target:
      kind: Service
      name: jobset-controller-manager-metrics-service
    patch: |-
      - op: add
        path: /spec/selector/control-plane
        value: kubeflow-trainer-v2-jobset
  - target:
      kind: Service
      name: jobset-webhook-service
    patch: |-
      - op: add
        path: /spec/selector/control-plane
        value: kubeflow-trainer-v2-jobset