apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../overlays/manager
  - ../../overlays/runtimes
  - kubeflow-trainer-roles.yaml

patches:
  - path: patches/remove-namespace.yaml
  - target:
      kind: Deployment
      name: kubeflow-trainer-controller-manager
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/control-plane
        value: kubeflow-trainer-v2